name: Monitor Google Drive Webhook Cron Job

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  monitor-webhooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Monitor Webhooks
        run: node cronRunner.js
